# Production environment values
replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

env:
  NODE_ENV: production
  # Database configuration
  DB_TYPE: postgres
  DB_PORT: "5432"
  DB_HOST: ""
  DB_USER: ""
  DB_NAME: ""
  DB_SCHEMA: ""
  K8S_SERVICE_URL: ""
  # CORS configuration for prod
  CORS_ORIGIN: "https://coregame.sh"
  AUTH_COOKIE_NAME: "token"
  AUTH_COOKIE_DOMAIN: ".coregame.sh"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://coregame.sh"
    nginx.ingress.kubernetes.io/enable-cors: "true"
#    nginx.ingress.kubernetes.io/limit-rps: "10"
#    nginx.ingress.kubernetes.io/limit-burst: "20"
#    nginx.ingress.kubernetes.io/limit-connections: "50"
  hosts:
    - host: api.coregame.sh
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - api.coregame.sh
      secretName: api-coregame-de-tls

nodeSelector: {}
tolerations: []
affinity: {}
