# Development environment values
replicaCount: 1

autoscaling:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  # Database configuration
  DB_TYPE: postgres
  DB_PORT: "5432"
  DB_HOST: ""
  DB_USER: ""
  DB_NAME: ""
  DB_SCHEMA: ""
  K8S_SERVICE_URL: ""
  # CORS configuration for dev
  CORS_ORIGIN: "https://dev.coregame.sh"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://dev.coregame.sh"
    nginx.ingress.kubernetes.io/enable-cors: "true"
#    nginx.ingress.kubernetes.io/limit-rps: "5"
#    nginx.ingress.kubernetes.io/limit-burst: "10"
#    nginx.ingress.kubernetes.io/limit-connections: "20"
  hosts:
    - host: dev.api.coregame.sh
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - dev.api.coregame.sh
      secretName: dev-api-coregame-de-tls

nodeSelector: {}
tolerations: []
affinity: {}
