apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wiki-redirect
  namespace: production
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/permanent-redirect: "https://coregame.sh/wiki"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - wiki.coregame.sh
      secretName: wiki-coregame-tls
  rules:
    - host: wiki.coregame.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dummy-service
                port:
                  number: 80
