apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}-secrets
  labels:
    {{- include "api.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | b64enc | quote }}
  DB_URL: {{ .Values.secrets.DB_URL | b64enc | quote }}
  API_SECRET_ENCRYPTION_KEY: {{ .Values.secrets.API_SECRET_ENCRYPTION_KEY | b64enc | quote }}
  RABBITMQ_URL: {{ .Values.secrets.RABBITMQ_URL | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | b64enc | quote }}
  CLIENT_GITHUB_SECRET: {{ .Values.secrets.CLIENT_GITHUB_SECRET | b64enc | quote }}
  FORTYTWO_CLIENT_SECRET: {{ .Values.secrets.FORTYTWO_CLIENT_SECRET | b64enc | quote }}
